# Generated by Django 4.0.5 on 2022-08-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_alter_empleado_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('2', 'ECONOMISTA'), ('0', 'CONTADOR'), ('3', 'OTRO'), ('1', 'ADMINISTRADOR')], max_length=1, verbose_name='trabajo'),
        ),
    ]
