# Generated by Django 4.0.5 on 2022-08-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_empleado_hoja_vida_alter_empleado_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=b'I01\n', max_length=60, verbose_name='Nombres Completos'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('3', 'OTRO'), ('0', 'CONTADOR'), ('1', 'ADMINISTRADOR'), ('2', 'ECONOMISTA')], max_length=1, verbose_name='trabajo'),
        ),
    ]
