# Generated by Django 4.0.5 on 2022-09-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0009_empleado_full_name_alter_empleado_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('2', 'ECONOMISTA'), ('7', 'DIRECTOR COMERCIAL'), ('8', 'DIRECTOR MARKETING'), ('6', 'DIRECTOR DE OPÉRACIONES'), ('0', 'CONTADOR'), ('11', 'SISTEMA'), ('1', 'ADMINISTRADOR'), ('4', 'SEGURIDAD'), ('10', 'DIRECTOR FINANCIERO'), ('3', 'VENTAS'), ('5', 'DIRECTOR EJECUTIVO'), ('12', 'OTRO'), ('9', 'DIRECTOR DE RECURSOS HUMANOS')], max_length=20, verbose_name='trabajo'),
        ),
    ]
